# Analise de vendas - Cafeteria

## Objetivo do Projeto

O objetivo desse projeto é iniciar o tratamento e uma analise exploratoria dos dados de vendas da cafeteria, com o objetivo de entender melhor as vendas e realizar a criacao de um dashboard.

Durante o projeto serão realizadas as etapas de:

- Compreensão dos dados;
- Limpeza e tratamento dos dados;
- Tradução dos dados
- Analise exploratoria dos dados;
- Visualizações dos dados;
- Construcao de um dashboard.

---

## 1. Carregamento do dataset

### Importando as bibliotecas

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Leitura do dataset

In [2]:
df = pd.read_csv('./data/coffeeshop.csv')

pd.options.display.float_format = '{:.2f}'.format

### Entendimento inicial dos dados

In [3]:
df.head()

,transaction_id,transaction_date,transaction_time,store_id,store_location,product_id,transaction_qty,unit_price,Total_Bill,product_category,product_type,product_detail,Size,Month Name,Day Name,Hour,Month,Day of Week
0,114301,01-06-2023,11:33:29,3,Astoria,45,1,3.00,3.00,Tea,Brewed herbal tea,Peppermint,Large,June,Thursday,11,6,3
1,115405,02-06-2023,11:18:24,3,Astoria,45,1,3.00,3.00,Tea,Brewed herbal tea,Peppermint,Large,June,Friday,11,6,4
2,115478,02-06-2023,12:02:45,3,Astoria,45,1,3.00,3.00,Tea,Brewed herbal tea,Peppermint,Large,June,Friday,12,6,4
3,116288,02-06-2023,19:39:47,3,Astoria,45,1,3.00,3.00,Tea,Brewed herbal tea,Peppermint,Large,June,Friday,19,6,4
4,116714,03-06-2023,12:24:57,3,Astoria,45,1,3.00,3.00,Tea,Brewed herbal tea,Peppermint,Large,June,Saturday,12,6,5

In [4]:
print(f"O dataset possui {df.shape[0]} linhas e {df.shape[1]} colunas.")

O dataset possui 149116 linhas e 18 colunas.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  str
 2   transaction_time  149116 non-null  str
 3   store_id          149116 non-null  int64
 4   store_location    149116 non-null  str
 5   product_id        149116 non-null  int64
 6   transaction_qty   149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   Total_Bill        149116 non-null  float64
 9   product_category  149116 non-null  str
 10  product_type      149116 non-null  str
 11  product_detail    149116 non-null  str
 12  Size              149116 non-null  str
 13  Month Name        149116 non-null  str
 14  Day Name          149116 non-null  str
 15  Hour              149116 non-null  int64
 16  Month             149116 non-null  int64
 17  Day of Week       149116 non-null  int64
dtypes: float64(2), int64(7), str(9)
memory usage: 32.8 MB

In [6]:
df.describe()

,transaction_id,store_id,product_id,transaction_qty,unit_price,Total_Bill,Hour,Month,Day of Week
count,149116.00,149116.00,149116.00,149116.00,149116.00,149116.00,149116.00,149116.00,149116.00
mean,74737.37,5.34,47.92,1.44,3.38,4.69,11.74,3.99,2.98
std,43153.60,2.07,17.93,0.54,2.66,4.23,3.76,1.67,2.00
min,1.00,3.00,1.00,1.00,0.80,0.80,6.00,1.00,0.00
25%,37335.75,3.00,33.00,1.00,2.50,3.00,9.00,3.00,1.00
50%,74727.50,5.00,47.00,1.00,3.00,3.75,11.00,4.00,3.00
75%,112094.25,8.00,60.00,2.00,3.75,6.00,15.00,5.00,5.00
max,149456.00,8.00,87.00,8.00,45.00,360.00,20.00,6.00,6.00

## Descrição das Colunas do Dataset

| Coluna | Descrição |
|---|---|
| `transaction_id` | Identificador único de cada transação realizada. |
| `transaction_date` | Data em que a compra foi efetuada. |
| `transaction_time` | Horário exato da transação. |
| `store_id` | Identificador único da loja onde a venda ocorreu. |
| `store_location` | Localização ou unidade da cafeteria onde a compra foi realizada. |
| `product_id` | Identificador único do produto vendido. |
| `transaction_qty` | Quantidade de itens comprados na transação. |
| `unit_price` | Preço unitário do produto. |
| `Total_Bill` | Valor total pago na compra (`quantidade × preço unitário`). |
| `product_category` | Categoria geral do produto vendido (ex.: Tea, Coffee, Bakery). |
| `product_type` | Tipo específico do produto dentro da categoria. |
| `product_detail` | Descrição detalhada ou sabor do produto. |
| `Size` | Tamanho do produto vendido (Small, Medium, Large, etc.). |
| `Month Name` | Nome do mês em que a transação ocorreu. |
| `Day Name` | Nome do dia da semana da transação. |
| `Hour` | Hora extraída do horário da transação. |
| `Month` | Número do mês da transação. |
| `Day of Week` | Número correspondente ao dia da semana. |

In [7]:
coluna_categorica = df.select_dtypes(include=['string']).columns
coluna_numerica = df.select_dtypes(include=['number']).columns

coluna_categorica = coluna_categorica.drop(['transaction_date', 'transaction_time'])

In [8]:
for coluna in coluna_categorica:
    print(f'Os valores unicos da coluna {coluna} são:')
    for index in df[coluna].unique():
        print(f' - {index}')

Os valores unicos da coluna store_location são:
 - Astoria
 - Lower Manhattan
 - Hell's Kitchen
Os valores unicos da coluna product_category são:
 - Tea
 - Coffee
 - Bakery
 - Drinking Chocolate
 - Flavours
 - Loose Tea
 - Packaged Chocolate
 - Branded
 - Coffee beans
Os valores unicos da coluna product_type são:
 - Brewed herbal tea
 - Brewed Black tea
 - Brewed Green tea
 - Brewed Chai tea
 - Drip coffee
 - Organic brewed coffee
 - Barista Espresso
 - Gourmet brewed coffee
 - Scone
 - Pastry
 - Premium brewed coffee
 - Hot chocolate
 - Biscotti
 - Sugar free syrup
 - Regular syrup
 - Herbal tea
 - Black tea
 - Chai tea
 - Green tea
 - Drinking Chocolate
 - Organic Chocolate
 - Clothing
 - Housewares
 - Espresso Beans
 - Green beans
 - Organic Beans
 - Premium Beans
 - Gourmet Beans
 - House blend Beans
Os valores unicos da coluna product_detail são:
 - Peppermint
 - Lemon Grass
 - Earl Grey
 - English Breakfast
 - Serenity Green Tea
 - Traditional Blend Chai
 - Our Old Time Diner Blend
 - Brazilian
 - Espresso shot
 - Ouro Brasileiro shot
 - Columbian Medium Roast
 - Ethiopia
 - Oatmeal Scone
 - Morning Sunrise Chai
 - Almond Croissant
 - Chocolate Croissant
 - Jumbo Savory Scone
 - Jamaican Coffee River
 - Cappuccino
 - Latte
 - Sustainably Grown Organic
 - Dark chocolate
 - Croissant
 - Ginger Biscotti
 - Chocolate Chip Biscotti
 - Hazelnut Biscotti
 - Ginger Scone
 - Cranberry Scone
 - Scottish Cream Scone
 - Sugar Free Vanilla syrup
 - Hazelnut syrup
 - Chocolate syrup
 - Carmel syrup
 - Spicy Eye Opener Chai
 - Chili Mayan
 - I Need My Bean! T-shirt
 - I Need My Bean! Diner mug
 - I Need My Bean! Latte cup
 - Espresso Roast
 - Primo Espresso Roast
 - Guatemalan Sustainably Grown
 - Organic Decaf Blend
 - Civet Cat
 - Jamacian Coffee River
 - Brazilian - Organic
Os valores unicos da coluna Size são:
 - Large
 - Regular
 - Not Defined
 - Small
Os valores unicos da coluna Month Name são:
 - June
 - May
 - March
 - April
 - January
 - February
Os valores unicos da coluna Day Name são:
 - Thursday
 - Friday
 - Saturday
 - Sunday
 - Monday
 - Wednesday
 - Tuesday

---

# 2. Limpeza e Tratamento dos Dados

Após a análise inicial do dataset, foi possível observar que não existem valores ausentes, registros duplicados e nem valores despadronizados relevantes que necessitem tratamento.

Dessa forma, esta etapa sera ignorada

OBS: deixei passar um café em especifico que encontrei na tradução dos produtos

In [9]:
df['product_detail'] = df['product_detail'].replace('Jamacian Coffee River', 'Jamaican Coffee River')

## 3. Tradução dos Dados

In [ ]:
# Tradução dos valores
# for coluna, valores in traducao_valores.items():
#    df[coluna] = df[coluna].replace(valores)

# Tradução das colunas
# df.rename(columns=traducao_colunas, inplace=True)

In [13]:
df.head()

,transacaoID,data_da_transacao,hora_da_transacao,lojaID,localizacao_loja,id_do_produto,quantidade_vendida,valor_unitario,valor_total,categoria_do_produto,tipo_do_produto,descricao_do_produto,tamanho,nome_do_mes,nome_do_dia,hora,mes,dia_da_semana
0,114301,01-06-2023,11:33:29,3,Astoria,45,1,3.00,3.00,Chá,Chá Herbal,Peppermint,Grande,Junho,Quinta-feira,11,6,3
1,115405,02-06-2023,11:18:24,3,Astoria,45,1,3.00,3.00,Chá,Chá Herbal,Peppermint,Grande,Junho,Sexta-feira,11,6,4
2,115478,02-06-2023,12:02:45,3,Astoria,45,1,3.00,3.00,Chá,Chá Herbal,Peppermint,Grande,Junho,Sexta-feira,12,6,4
3,116288,02-06-2023,19:39:47,3,Astoria,45,1,3.00,3.00,Chá,Chá Herbal,Peppermint,Grande,Junho,Sexta-feira,19,6,4
4,116714,03-06-2023,12:24:57,3,Astoria,45,1,3.00,3.00,Chá,Chá Herbal,Peppermint,Grande,Junho,Sábado,12,6,5